packages:
  - "Client/public-frontend" # Public frontend (main site)
  - "Client/retailer-frontend" # New Retailer frontend (private)
  - "Client/supplier-frontend" # Supplier frontend (private)
  - "Server" # Shared backend
